name: tensor
description: Tensor library for Dart using libtorch FFI.
version: 1.0.0
repository: https://github.com/tejainece/tensor

environment:
  sdk: ^3.10.0

dependencies:
  ffi: ^2.1.4
  universal_io: ^2.2.0
  collection: ^1.19.1
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  yaml: ^3.1.3
